### PR TITLE
handling empty filename

### PR DESCRIPTION
**Pull request by korbai**
Hello, I use bootstrap-fileinput and sometimes it send empty filename, so it will be useful if this package can handle this situation. Without this I got EISDIR error in save-to module.

### CODE REVIEW

**Comment by fengmk2** [comment]
Great job!  :cool: 

Can you add some tests for this fix?

**Comment by korbai** [comment]
Sure, I added.

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
co-multipart@1.0.0 now!

**Pull request merged**
