### PR TITLE
Dep co busboy

### PR DESCRIPTION
**Pull request by haoxins**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
@fengmk2 any advice?

**Comment by fengmk2** [comment]
LGTM

**Comment by fengmk2** [comment]
Need another +1

**Comment by fengmk2** [comment]
cc @jonathanong @dead-horse

**Comment by jonathanong** [comment]
i don't use this... no idea

**Comment by fengmk2** [comment]
OK, let's merge and publish a major version.

**Comment by fengmk2** [comment]
co-multipart@2.0.0

**Comment by haoxins** [comment]
:clap:

**Pull request merged**
